CREATE TABLE `member` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '회원아이디',
  `name` VARCHAR(10) DEFAULT NULL COMMENT '회원명',
  `image_name` VARCHAR(50) DEFAULT NULL COMMENT '이미지파일명',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8